// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pcviofkusmybzfdheqrl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBjdmlvZmt1c215YnpmZGhlcXJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5MDgzNTUsImV4cCI6MjA2NDQ4NDM1NX0.y211Z8AxukvKOUxHdFTfBD_8cJJ5XbRM6a6ZeQ81fKQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);